'''

389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''


s = "abcd"
t = "abcde"
Output =  "e"

s= ""
t = "y"
Output = "y"    

s = 'a'
t = 'aa'


def findTheDifference(s,t):
    ltr1 = []

    for i in t:
        if i not in s:
            ltr1.append(i)
    return ltr1[0]

    else:
        return s

    
    # print(ltr)


print(findTheDifference(s ,t))