'''

389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
'''


s = "abcd"
t = "abcde"
Output =  "e"

# s= ""
# t = "y"
# Output = "y"    

# s = 'a'
# t = 'aa'

# Output = "a"   


def findTheDifference(s,t):

    s1 = set(s)
    t1 = set(t)

    str1 = ''
    dict1 = {}
    dict2 = {}

    for i in s1:
        k = s.count(i)
        dict1.update({i:k})

    for i in t1:
        m = t.count(i)
        dict2.update({i:m})

    for i,j in dict2.items():
        if i not in dict1:
            str1 = str1+i
            return str1

        elif i in dict1 and j>dict1.get(i):
            str1 = str1+i
            return str1
    
print(findTheDifference(s ,t))